# Generated by Django 5.2.10 on 2026-01-17 20:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_contact_phone_con'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pro', models.CharField(max_length=100)),
                ('description_pro', models.CharField(max_length=1500)),
                ('price_pro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_pro', models.ImageField(upload_to='')),
                ('shortDescription_pro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('message', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.user')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_by_evaluation', to='produtos.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.product')),
            ],
        ),
    ]
