# Generated by Django 5.2.10 on 2026-01-19 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('uploader', '0002_alter_document_id_alter_image_id'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_by_evaluation', to='produtos.product'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.user'),
        ),
    ]
