# Generated by Django 5.2.10 on 2026-01-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_coupon_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
