# Generated by Django 5.2.6 on 2025-09-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_descricao_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fotoPrincipal',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fotoSecundaria',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fotoTercearia',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
