# Generated by Django 5.2.10 on 2026-01-18 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_purchase_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='value',
            new_name='value_com',
        ),
    ]
