# Generated by Django 5.2.6 on 2025-09-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_fotoprincipal_produto_fotosecundaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fotoPrincipal',
            field=models.ImageField(null=True, upload_to='media/produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fotoSecundaria',
            field=models.ImageField(null=True, upload_to='media/produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fotoTercearia',
            field=models.ImageField(null=True, upload_to='media/produtos/'),
        ),
    ]
