# Generated by Django 5.2.10 on 2026-01-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_rename_value_purchase_value_com'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='name_cup',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_pro',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_pro',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_pro',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_pro',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shortDescription_pro',
            new_name='shortDescription',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='qrCode_com',
            new_name='qrCode',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='value_com',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='value_cup',
        ),
        migrations.AddField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
