# Generated by Django 5.2.6 on 2025-09-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_fotoprincipal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='fotoTercearia',
            new_name='fotoTerciaria',
        ),
    ]
