# Generated by Django 5.2.7 on 2025-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_rename_fototercearia_produto_fototerciaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fotoTerciaria',
        ),
        migrations.AlterField(
            model_name='produto',
            name='fotoPrincipal',
            field=models.ImageField(null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fotoSecundaria',
            field=models.ImageField(null=True, upload_to='produtos/'),
        ),
    ]
