# Generated by Django 5.2.6 on 2025-09-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_sobrenome_usuario_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='/default.png', upload_to='perfil/'),
        ),
    ]
