# Generated by Django 5.2.6 on 2025-09-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='/perfil/default.png', upload_to='perfil/'),
        ),
    ]
