# Generated by Django 5.2.6 on 2025-09-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='usuario/default.png', upload_to='media/usuario'),
        ),
    ]
