# Generated by Django 5.2.10 on 2026-01-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100, unique=True)),
                ('photo_user', models.ImageField(upload_to='')),
                ('fullName_user', models.CharField(max_length=200)),
                ('email_user', models.EmailField(max_length=255, unique=True)),
                ('senha_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_con', models.CharField(max_length=100)),
                ('message_con', models.CharField(max_length=2000)),
                ('phone_con', models.IntegerField(max_length=16)),
                ('email_con', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_by_email', to='usuarios.user', to_field='email_user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_by_username', to='usuarios.user', to_field='name_user')),
            ],
        ),
    ]
