# Generated by Django 5.2.10 on 2026-01-19 19:06

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0002_alter_document_id_alter_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('photo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=2000)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_by_email', to='usuarios.user', to_field='email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_by_name', to='usuarios.user', to_field='name')),
            ],
        ),
    ]
