# Generated by Django 5.2.10 on 2026-01-19 00:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_contact_phone_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email_con',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message_con',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_con',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='topic_con',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fullName_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='senha_user',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contact_by_email', to='usuarios.user', to_field='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='topic',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='senha',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_by_username', to='usuarios.user', to_field='name'),
        ),
    ]
